"""delete column

Revision ID: d33b3459079a
Revises: 44d52cef83aa
Create Date: 2025-12-01 09:28:28.928962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33b3459079a'
down_revision: Union[str, Sequence[str], None] = '44d52cef83aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_problem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_problem', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
